#!/usr/bin/env bash

change_ext () {
	if test ${1##*.} = xml; then
		echo ${1%.*}.nest
	else
		echo ${1}.nest
	fi
}

for file in "$@"; do
sed --regexp-extended \
	-e 's!<([^ /]+)>!\\\1<!g' \
	-e 's!<([^ /]+)([ \r\n]+([^<>]*))* />!\\\1[\3]<>!g' \
	-e 's!<([^ /]+)([ \r\n]+([^<>]*))*>!\\\1[\3]<!g' \
	-e 's!</([^ ]+)>!>!g' \
	$file > $(change_ext $file)
done
