#!/usr/bin/env bash

change_ext () {
	case ${1##*.} in
		xml)    echo ${1%.*}.nest ;;
		html)   echo ${1%.*}.nest ;;
		xhtml)  echo ${1%.*}.nest ;;
		*)      echo ${1}.nest ;;
	esac
}

for file in "$@"; do
sed --regexp-extended \
	-e 's!<([^ </>!?]+)>([^>]+)</\1>$!\\\1: \2!g' \
	-e 's!<([^ </>!?]+)>!\\\1<!g' \
	-e 's!<([^ </>!?]+)([ \r\n]+([^<>]+))* +/>!\\\1[\3]<>!g' \
	-e 's!<([^ </>!?]+)([ \r\n]+([^<>]+))*>!\\\1[\3]<!g' \
	-e 's!</([^ </>!?]+)>!>!g' \
	$file > $(change_ext $file)
done
