#!/usr/bin/env bash

change_ext () {
	case ${1##*.} in
		xml)    echo ${1%.*}.nest ;;
		html)   echo ${1%.*}.nest ;;
		xhtml)  echo ${1%.*}.nest ;;
		*)      echo ${1}.nest ;;
	esac
}

#	The first regex transform element that are opened and then closed at the end
#	of the same line to use NEST's oneline form.

#	The rests transform XML tags to NEST's bracket form: the second regex
#	converts opening tags without attributes, the third converts self-closing
#	tags with attributes, the fourth converts opening tags with attributes, and
#	the fifth convert closing tags.

for file in "$@"; do
sed --regexp-extended \
	-e 's!<([^ </>!?]+)>([^>]+)</\1>$!\\\1: \2!g' \
	-e 's!<([^ </>!?]+)>!\\\1<!g' \
	-e 's!<([^ </>!?]+)([ \r\n]+([^<>]+))* +/>!\\\1[\3]<>!g' \
	-e 's!<([^ </>!?]+)([ \r\n]+([^<>]+))*>!\\\1[\3]<!g' \
	-e 's!</([^ </>!?]+)>!>!g' \
	$file > $(change_ext $file)
done
